baro_inventory: ./metadata/station_BW_FFBI.xml
baro_seed: BW.FFBI..BDO
cc_threshold: 0.7
data_source: sds
fdsn_server: null
fmax: 0.01
fmin: 0.0001
metadata_correction: true
out_seed: null
overlap: 0.5
path_to_baro_data: /home/andbro/bay200/mseed_online/archive/
path_to_figures: ./figures
path_to_seis_data: /home/andbro/freenas/temp_archive/
remove_baro_gain: true
remove_baro_response: false
remove_seis_response: false
remove_seis_sensitivity: true
sampling_rate: 1.0
seis_inventory: ./metadata/station_BW_ROMY.xml
seis_seeds:
- BW.ROMY.40.BJZ
- BW.ROMY.40.BJN
- BW.ROMY.40.BJE
station_elevation: 560.0
station_latitude: 48.162941
station_longitude: 11.275501
step: 1
t1: '2024-03-24T14:00:00.000000Z'
t2: '2024-03-24T18:00:00.000000Z'
tbeg: '2024-03-24T15:00:00.000000Z'
tend: '2024-03-24T17:00:00.000000Z'
time_buffer: 3600.0
verbose: true
win_length_sec: 300.0
