baro_inventory: ./metadata/station_BW_FFBI.xml
baro_seed: BW.FFBI..BDO
cc_threshold: 0.7
data_source: file
fdsn_server: null
fmax: 0.01
fmin: 0.0001
metadata_correction: false
out_seed: null
overlap: 0.5
path_to_baro_data: ./data/FFBI_DROMY_20240315.mseed
path_to_figures: ./figures
path_to_seis_data: ./data/FFBI_DROMY_20240315.mseed
remove_baro_gain: true
remove_baro_response: false
remove_seis_response: false
remove_seis_sensitivity: false
sampling_rate: 1.0
seis_inventory: ./metadata/station_BW_DROMY.xml
seis_seeds:
- BW.DROMY..HHZ
- BW.DROMY..HHN
- BW.DROMY..HHE
station_elevation: 560.0
station_latitude: 48.162941
station_longitude: 11.275501
step: 1
t1: '2024-03-15T14:00:00.000000Z'
t2: '2024-03-15T19:00:00.000000Z'
tbeg: '2024-03-15T15:00:00.000000Z'
tend: '2024-03-15T18:00:00.000000Z'
time_buffer: 3600.0
verbose: true
win_length_sec: 300.0
