baro_inventory: ./metadata/station_BW_FFBI.xml
baro_seed: BW.FFBI..BDO
cc_threshold: 0.7
data_source: sds
fdsn_server: null
fmax: 0.01
fmin: 0.0001
metadata_correction: true
out_seed: null
overlap: 0.5
path_to_baro_data: /home/andbro/bay200/mseed_online/archive/
path_to_figures: ./figures
path_to_seis_data: /home/andbro/bay200/mseed_online/archive/
remove_baro_gain: true
remove_baro_response: false
remove_seis_response: true
remove_seis_sensitivity: false
sampling_rate: 1.0
seis_inventory: ./metadata/station_GR_FUR.xml
seis_seeds:
- GR.FUR..HHZ
- GR.FUR..HHN
- GR.FUR..HHE
station_elevation: 560.0
station_latitude: 48.162941
station_longitude: 11.275501
step: 1
t1: '2024-08-29T14:00:00.000000Z'
t2: '2024-08-29T18:00:00.000000Z'
tbeg: '2024-08-29T15:00:00.000000Z'
tend: '2024-08-29T17:00:00.000000Z'
time_buffer: 3600.0
verbose: true
win_length_sec: 300.0
