baro_inventory: ./metadata/station_BW_FFBI.xml
baro_seed: BW.FFBI..BDO
cc_threshold: 0.7
data_source: sds
fdsn_server: null
fmax: 0.01
fmin: 0.0001
metadata_correction: true
out_seed: null
overlap: 0.5
path_to_baro_data: /home/andbro/bay200/mseed_online/archive/
path_to_figures: ./figures
path_to_seis_data: /home/andbro/freenas/romy_archive/
pre_filter: !!python/tuple
- 5.0e-05
- 0.0001
- 1.0
- 2.0
remove_baro_response: true
remove_seis_response: true
remove_seis_sensitivity: false
sampling_rate: 1.0
seis_inventory: ./metadata/station_BW_DROMY.xml
seis_seeds:
- BW.DROMY..HHZ
- BW.DROMY..HHN
- BW.DROMY..HHE
station_elevation: 560.0
station_latitude: 48.162941
station_longitude: 11.275501
step: 1
t1: '2024-03-12T08:00:00.000000Z'
t2: '2024-03-12T19:00:00.000000Z'
tbeg: '2024-03-12T09:00:00.000000Z'
tend: '2024-03-12T18:00:00.000000Z'
time_buffer: 3600.0
verbose: true
win_length_sec: 300.0
